### ISSUE TITLE
safari에서 업로드 하면 이렇게 음악은 올라가는데 진행이 안됩니다.

### ISSUE THREAD

**Issue by botserv** [largeden/xpresseditor_axupload5#11]
무시하고 업로드 할 경우 오류코드인가요? 페이지 소스가 나오네요.
![12](https://cloud.githubusercontent.com/assets/10341560/9610441/8b41d020-5114-11e5-9443-b4d8c804509b.png)
![11](https://cloud.githubusercontent.com/assets/10341560/9610445/9a4502fe-5114-11e5-994f-add9180d547c.png)

**Comment by largeden** [comment]
@botserv 
다른 브라우저에서는 증상이 이떤가요?
문제의 첨부파일보다 용량이 큰거나 작은 파일은 어떤가요?

자체 테스트결과 정상적으로 mp3 업로드를 확인했습니다. #5.mp3(9MB)

**Comment by botserv** [comment]
Mac os가 없어서 ㅠ 유저분이 제보해주신건데 버전정보랑 자세히 물어보고 다시 문의드릴께요 답변감사합니다

**Comment by botserv** [comment]
현재증상은 업로더 퍼센트율이 안올라간다고 합니다 php에 맥스 사이즈는 120메가로 되어있습니다

**Comment by largeden** [comment]
@botserv 

이슈는 본인의 경험을 토대로 등록해주셨으면 감사하겠습니다.
Mac OS 사파리에서 문제 없이 올라갔습니다. 해당분에게 다른 브라우저로 테스트 해보시라고 이야기해주십시오.

증상이 확인되지 않으면 개선 검토가 어렵습니다.

#9 이슈와 같이 동영상 촬영 등이 가능하다면 만들어서 올려주시기 바랍니다.

**Comment by botserv** [comment]
우선 번거롭게 해드려서 죄송합니다.

해당 유저에게 다른 브라우저로 테스트할 수 있는지 문의해보겠습니다.

현재 이슈가 생긴 사이트 URL은 http://www.clubsound.kr/pointtest 입니다.


-
사파리 버전 6.0.5 버전입니다. 소스는 다시 확인해보려고 하니 노래가 업로드 안 된 상태로 그냥 제목과 내용글만 올라가네요.

**Comment by largeden** [comment]
@botserv 
알려주신 URL에 테스트 해봤습니다.
문제없이 업로드 되었습니다.
버그 아님으로 이 건은 닫겠습니다.

추가적으로 질문 있으시면 이어서 코멘트 남겨주시거나 새로운 이슈를 적어주십시오.
