### ISSUE TITLE
safari에서 첨부파일 업로드할때 에러가 나네요..ㅠㅠ

### ISSUE THREAD

**Issue by Jeounghyunpark** [largeden/xpresseditor_axupload5#12]
파일전송에 실패 하였습니다. 서버에서 에러가 리턴 되었습니다. 콘솔창을 확인 하세요.

라는 오류 메세지가 출력되는데요

어떻게 해야 할까요

![2015-11-20 11 33 04](https://cloud.githubusercontent.com/assets/5316787/11290479/7d6c9c56-8f7a-11e5-896a-67b3aff16ab9.png)

**Comment by largeden** [comment]
OS는 무엇입니까?
다른 브라우저에서는 어떻습니까?
사용중인 xe 버전은 무엇입니까?
가능하시다면 제가 테스트 할 수 있도록 홈페이지 주소를 남겨주세요.

**Comment by Jeounghyunpark** [comment]
OS : MAC OS X El Capitan (10.11.1)
XE : 1.8.14
http://pjhyun25.cafe24.com/
테스트 계정 : id: test // pw: test

관리자 계정으로 로그인했을때는 첨부가 잘 되지만
다른 계정으로 로그인 해서 첨부 했을때 위와같은 문제가 발견되었으며 (사파리 테스트)
크롬에서도 동일한 문제가 발생합니다.

**Comment by largeden** [comment]
CKeditor에서는 업로드가 되십니까?
순정 xpresseditor에서는 업로드가 되십니까?
xecore이외에 별도로 설치한 애드온, 모듈이 있으십니까?

관리자가 사용된다는 것은 해당 스킨 사용 문제와 무관할 가능성이 있습니다.
제 사이트에서 테스트해보았지만 별다른 문제점이 없었습니다.
타 애드온, 모듈에 의한 관리 권한 등으로 업로드가 비허용 되어있는지 점검해주세요.

**Comment by Jeounghyunpark** [comment]
xpresseditor 에서도 업로드가 안되네요 ...ㅠ
애드온이나 모듈은 첨부파일 및 회원권한에 관련된건 하나도 설치하지 않았습니다 ....
호스팅 업체쪽의 문제일까요???

<img width="589" alt="2015-11-20 2 28 14" src="https://cloud.githubusercontent.com/assets/5316787/11292544/f9ae5e0e-8f92-11e5-80b1-23fe2afeb083.png">

**Comment by largeden** [comment]
공식 홈페이지에 문의 해보시고 호스팅 업체에도 문의해보세요.

이 증상은 axupload5 스킨의 문제가 아님으로 종료할게요.
