### ISSUE TITLE
임시 저장글을 불러 오고 난 후 해당 글 파일 첨부시 파일이 두번 등록 됩니다.

### ISSUE THREAD

**Issue by mactopia** [largeden/xpresseditor_axupload5#9]
저만 그런건지 싶어 안올렸는데 혹시나 해서 증상 올려 봅니다

**Comment by largeden** [comment]
@mactopia 

이곳에서 테스트해보세요. 전 잘 되는거 같습니다.
그리고 브라우저는 뭘로 테스트하신건가요? 브라우저 캐시같은거 있음 지워보시고요.

XE ver 1.8.6
http://romanesque.me/index.php?mid=board

id: test@test.com
pw: testtest

**Comment by mactopia** [comment]
똑같이 증상 재현 됩니다. OSX 사파리 입니다. ^^; 캐쉬는 안지워 봤지만 첫 방문한 사이트 에 새로운 이미지로 했으니 캐쉬 문제는 아닐거라 생각해봅니다.

**Comment by largeden** [comment]
순서를 자세히 적어주시곘어요?

OSX 사파리에서 문제가 없거든요.

저는 아래와 같이 해보았습니다.
- 게시판 글쓰기 클릭 후 타이틀, 본문에 test라고 적고 임시 저장버튼 클릭
- 뒤로 가기 한 뒤에 다시 글쓰기 버튼 클릭. 이번에는 불러오기 클릭하여 다시 글 불러옴
- 파일 1개 첨부
- 한개가 첨부됨

**Comment by mactopia** [comment]
아. 제가 표현이 틀렸었네요. 임시저장이 아니라 자동저장입니다.

게시판 글쓰기 클릭 후 타이틀, 본문에 test라고 적고 일정 시간이 흐룬이후에
뒤로 가기 한 뒤에 다시 글쓰기 버튼 클릭. 저장된 글을 불러오겠습니까? 라고 질문이 나오면 클릭
파일 1개 첨부
두개가 첨부됨

- 이런 flow 라 할수 있습니다.

**Comment by largeden** [comment]
@mactopia 
설명대로 OSX 요세미티 사파리에서 진행하였는데 문제재현에 실패했습니다. 정상적으로 하나의 파일만 업로드 되었습니다.

다른 브라우저와 다른 컴퓨터에서 테스트해보시기 바랍니다. 그리고 지금 debugPrint걸어 놓고 있으니 문제재현 다시 한번 더 해주시고요.

**Comment by mactopia** [comment]
지금 다시 해봤습니다. ^^ 참고 부탁 합니다.

**Comment by mactopia** [comment]
OSX 파이어 폭스도 같은 증상입니다.

**Comment by mactopia** [comment]
https://www.dropbox.com/s/d4czdrul0i4izjk/test.mov?dl=0

테스트 재현 영상 입니다.

**Comment by largeden** [comment]
@mactopia 
영상 덕택에 재현 되었습니다. ^^
드래그앤 드롭을 쓰셨군요.

해당 문제는 자동 저장 불러오기 상태에서의 드래그앤 드롭에 의한 업로드만 생기는 문제점 입니다.
아마도 예전 버전부터 있었던 버그일듯 싶습니다.

일단 위 테스트 사이트는 증상이 안나오도록 조치해뒀는데요. 실제 개선된 버전을 배포하기까지는 불필요한 부분을 정리해야할 필요가 있어서 시일이 걸릴 듯 싶습니다. 당분간은 되도록 드래그앤 드롭은 피하고 버튼 클릭으로 올려주세요.

**Comment by mactopia** [comment]
아. 네^^ 감사합니다.

**Comment by largeden** [comment]
@mactopia 
덕분에 버그 개선되었습니다. 고맙습니다. ^^
XE 공홈에 배포시 업데이트 내역에 제보자 이름 올릴려는데 socialskyo로 적으면 될까요?

**Comment by socialskyo** [comment]
아..네.^^; 같습니다. 제가 다 고맙습니다. :-)
